name: Compilation des Radars CSV

on:
  push:
    paths:
      - 'data/*.csv'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Executer la fusion CSV
        run: python compile_data.py

      - name: Commit et Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add radars_complet.json
          
          # Vérifie si le fichier a changé
          if git diff --quiet && git diff --staged --quiet; then
            echo "Pas de nouveaux radars à ajouter."
            exit 0
          fi

          # On force la mise à jour pour éviter l'erreur de rejet
          git pull origin main --rebase
          git commit -m "Mise à jour base radars (CSV)"
          git push origin main
